name: Check Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  packages: read

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@aadec899646c8e0f34c52d9219c2faac36626b55 # v4.0.0

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@paritytech"

      - name: Install tooling
        run: |
            npm install -g markdownlint-cli
            markdownlint --version

      - name: Check Markdown
        env:
          CONFIG: .github/.markdownlint.yaml
        run: |
          markdownlint --config "$CONFIG" --ignore target .
